In [2]:
import sys

sys.path.append('/Users/datoapanta/Desktop/mma_2024/src/')
print(sys.path)                

['/Users/datoapanta/Desktop/mma_2024/src/models', '/Users/datoapanta/PycharmProjects/open_spiel', '/Users/datoapanta/PycharmProjects/open_spiel/build/python', '/Users/datoapanta/opt/anaconda3/envs/mma_2024/lib/python38.zip', '/Users/datoapanta/opt/anaconda3/envs/mma_2024/lib/python3.8', '/Users/datoapanta/opt/anaconda3/envs/mma_2024/lib/python3.8/lib-dynload', '', '/Users/datoapanta/opt/anaconda3/envs/mma_2024/lib/python3.8/site-packages', '/Users/datoapanta/Desktop/mma_2024/src/']


In [93]:
import config
from utils import audio_utils
from IPython.display import display
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer, LabelEncoder, LabelBinarizer
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle
from utils import audio_utils
import pickle
from utils import preprocessing

%load_ext autoreload
%autoreload 

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [61]:
# Splitting the data
data_splitted_dic = preprocessing.split_data(config.TRACKS_PATH)

# Get loaders
train_wav_paths, val_wav_paths, test_wav_paths = audio_utils.get_wav_paths(config.AUDIO_DIR, data_splitted_dic)
train_labels, val_labels, test_labels = preprocessing.get_labels(data_splitted_dic)

In [113]:
data_splitted_dic['labels'].unique()

['Hip-Hop', 'Pop', 'Folk', 'Experimental', 'Rock', 'International', 'Electronic', 'Instrumental']
Categories (16, object): ['Blues', 'Classical', 'Country', 'Easy Listening', ..., 'Pop', 'Rock', 'Soul-RnB', 'Spoken']

In [109]:
print(train_wav_paths[0])
print(data_splitted_dic['labels'].iloc[0])
print(train_labels[0])

print("\n", train_wav_paths[1])
print(data_splitted_dic['labels'].iloc[1])
print(train_labels[1])

print("\n", train_wav_paths[100])
print(data_splitted_dic['labels'].iloc[100])
print(train_labels[100])


i = 112
print("\n", train_wav_paths[i])
print(data_splitted_dic['labels'].iloc[i])
print(train_labels[i])

i = 1120
print("\n", train_wav_paths[i])
print(data_splitted_dic['labels'].iloc[i])
print(train_labels[i])


i = 3120
print("\n", train_wav_paths[i])
print(data_splitted_dic['labels'].iloc[i])
print(train_labels[i])


/Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/000/000002.wav
Hip-Hop
[0 0 0 1 0 0 0 0]

 /Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/000/000005.wav
Hip-Hop
[0 0 0 1 0 0 0 0]

 /Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/002/002096.wav
International
[0 1 0 0 0 0 0 0]

 /Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/003/003535.wav
Experimental
[0 0 0 0 0 0 1 0]

 /Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/037/037592.wav
Pop
[0 0 0 0 0 0 0 1]

 /Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/088/088868.wav
Electronic
[0 0 1 0 0 0 0 0]


In [103]:
i = 112
print("\n", train_wav_paths[i])
print(data_splitted_dic['labels'].iloc[i])
print(train_labels[i])


 /Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/003/003535.wav
Experimental
[0 0 0 0 0 0 1 0]


### Extracting 100 embeddings from VGGish

In [76]:
from vggish_model import VGGishModel
model = VGGishModel()

embeddings_train = model.forward("/Users/datoapanta/Desktop/mma_2024/joined.mp3")
print(embeddings_train.shape)

Using cache found in /Users/datoapanta/.cache/torch/hub/harritaylor_torchvggish_master


torch.Size([62, 128])


In [12]:
for i in range(100):
    embeddings_train = model.forward(train_wav_paths[i])
    output_file_path = f'embeddings/embedding_train_{i}.pkl'

    with open(output_file_path, 'wb') as f:
        pickle.dump(embeddings_train, f)

In [130]:
from utils.audio_utils import convert_m4a_to_wav

convert_m4a_to_wav("/Users/datoapanta/Desktop/missing_songs/099134/099134.m4a", "/Users/datoapanta/Desktop/missing_songs/099134/099134.wav")

Skipping tag ----:com.apple.iTunes:iTunSMPB due to error: [MP4FreeForm(b' 00000000 00000840 00000000 0000000000165BC0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000', <AtomDataType.UTF8: 1>)] not a Frame instance


In [122]:
df = pd.read_csv('/Users/datoapanta/Desktop/mma_2024/dataset/data/fma_metadata/raw_tracks.csv')
df.head()

track_id  album_id           album_title  \
0         2       1.0  AWOL - A Way Of Life   
1         3       1.0  AWOL - A Way Of Life   
2         5       1.0  AWOL - A Way Of Life   
3        10       6.0     Constant Hitmaker   
4        20       4.0                 Niris   

                                           album_url  artist_id artist_name  \
0  http://freemusicarchive.org/music/AWOL/AWOL_-_...          1        AWOL   
1  http://freemusicarchive.org/music/AWOL/AWOL_-_...          1        AWOL   
2  http://freemusicarchive.org/music/AWOL/AWOL_-_...          1        AWOL   
3  http://freemusicarchive.org/music/Kurt_Vile/Co...          6   Kurt Vile   
4  http://freemusicarchive.org/music/Chris_and_Ni...          4  Nicky Cook   

                                          artist_url  \
0            http://freemusicarchive.org/music/AWOL/   
1            http://freemusicarchive.org/music/AWOL/   
2            http://freemusicarchive.org/music/AWOL/   
3       http://freemusicarchive.org/music/Kurt_Vile/   
4  http://freemusicarchive.org/music/Chris_and_Ni...   

                            artist_website  \
0  http://www.AzillionRecords.blogspot.com   
1  http://www.AzillionRecords.blogspot.com   
2  http://www.AzillionRecords.blogspot.com   
3                      http://kurtvile.com   
4                                      NaN   

                                  license_image_file  \
0  http://i.creativecommons.org/l/by-nc-sa/3.0/us...   
1  http://i.creativecommons.org/l/by-nc-sa/3.0/us...   
2  http://i.creativecommons.org/l/by-nc-sa/3.0/us...   
3  http://i.creativecommons.org/l/by-nc-nd/3.0/88...   
4  http://i.creativecommons.org/l/by-nc-nd/3.0/88...   

                            license_image_file_large  ...  track_information  \
0  http://fma-files.s3.amazonaws.com/resources/im...  ...                NaN   
1  http://fma-files.s3.amazonaws.com/resources/im...  ...                NaN   
2  http://fma-files.s3.amazonaws.com/resources/im...  ...                NaN   
3  http://fma-files.s3.amazonaws.com/resources/im...  ...                NaN   
4  http://fma-files.s3.amazonaws.com/resources/im...  ...                NaN   

  track_instrumental track_interest track_language_code  track_listens  \
0                  0           4656                  en           1293   
1                  0           1470                  en            514   
2                  0           1933                  en           1151   
3                  0          54881                  en          50135   
4                  0            978                  en            361   

   track_lyricist track_number track_publisher      track_title  \
0             NaN            3             NaN             Food   
1             NaN            4             NaN     Electric Ave   
2             NaN            6             NaN       This World   
3             NaN            1             NaN          Freeway   
4             NaN            3             NaN  Spiritual Level   

                                           track_url  
0  http://freemusicarchive.org/music/AWOL/AWOL_-_...  
1  http://freemusicarchive.org/music/AWOL/AWOL_-_...  
2  http://freemusicarchive.org/music/AWOL/AWOL_-_...  
3  http://freemusicarchive.org/music/Kurt_Vile/Co...  
4  http://freemusicarchive.org/music/Chris_and_Ni...  

[5 rows x 39 columns]

In [129]:
track_id = 99134
row = df.loc[df['track_id'] == track_id]
display(row)
album_url = row['album_url'].values[0]
print(album_url)
track_file = row['track_file'].values[0]
print(track_file)

track_id  album_id                       album_title  \
68688     99134   16027.0  Live at the 2014 Golden Festival   

                                               album_url  artist_id  \
68688  http://freemusicarchive.org/music/Pontic_Fireb...      18011   

           artist_name                                         artist_url  \
68688  Pontic Firebird  http://freemusicarchive.org/music/Pontic_Fireb...   

                  artist_website  \
68688  http://www.bethcohen.com/   

                                      license_image_file  \
68688  http://i.creativecommons.org/l/by-nc-nd/3.0/us...   

                                license_image_file_large  license_parent_id  \
68688  http://fma-files.s3.amazonaws.com/resources/im...                6.0   

                                           license_title  \
68688  Attribution-Noncommercial-No Derivative Works ...   

                                             license_url tags  track_bit_rate  \
68688  http://creativecommons.org/licenses/by-nc-nd/3...   []        192000.0   

       track_comments track_composer track_copyright_c track_copyright_p  \
68688               0            NaN               NaN               NaN   

          track_date_created track_date_recorded  track_disc_number  \
68688  2/13/2014 05:54:19 PM                 NaN                  1   

      track_duration track_explicit track_explicit_notes  track_favorites  \
68688          05:08            NaN                  NaN                0   

                                              track_file  \
68688  music/WFMU/Pontic_Firebird/Live_at_the_2014_Go...   

                                            track_genres  \
68688  [{'genre_id': '296', 'genre_title': 'Dance', '...   

                                        track_image_file track_information  \
68688  https://freemusicarchive.org/file/images/album...               NaN   

       track_instrumental  track_interest track_language_code  track_listens  \
68688                   0            5292                 NaN           4992   

      track_lyricist  track_number track_publisher track_title  \
68688            NaN             4             NaN       Halay   

                                               track_url  
68688  http://freemusicarchive.org/music/Pontic_Fireb...

http://freemusicarchive.org/music/Pontic_Firebird/Live_at_the_2014_Golden_Festival_1238/
music/WFMU/Pontic_Firebird/Live_at_the_2014_Golden_Festival/Pontic_Firebird_-_04_-_Halay.mp3


In [119]:
df = pd.read_csv('/Users/datoapanta/Desktop/mma_2024/dataset/data/fma_metadata/tracks.csv')
df.head()

/var/folders/bz/yv6zpqcs0vgf1wt80wfp36t40000gn/T/ipykernel_47075/175430741.py:1: DtypeWarning: Columns (0,1,5,6,8,12,18,20,21,22,24,33,34,38,39,44,47,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/datoapanta/Desktop/mma_2024/dataset/data/fma_metadata/tracks.csv')


Unnamed: 0     album              album.1              album.2   album.3  \
0        NaN  comments         date_created        date_released  engineer   
1   track_id       NaN                  NaN                  NaN       NaN   
2          2         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
3          3         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
4          5         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   

     album.4 album.5      album.6  album.7   album.8  ...     track.10  \
0  favorites      id  information  listens  producer  ...  information   
1        NaN     NaN          NaN      NaN       NaN  ...          NaN   
2          4       1      <p></p>     6073       NaN  ...          NaN   
3          4       1      <p></p>     6073       NaN  ...          NaN   
4          4       1      <p></p>     6073       NaN  ...          NaN   

   track.11       track.12                                           track.13  \
0  interest  language_code                                            license   
1       NaN            NaN                                                NaN   
2      4656             en  Attribution-NonCommercial-ShareAlike 3.0 Inter...   
3      1470             en  Attribution-NonCommercial-ShareAlike 3.0 Inter...   
4      1933             en  Attribution-NonCommercial-ShareAlike 3.0 Inter...   

  track.14  track.15 track.16   track.17 track.18      track.19  
0  listens  lyricist   number  publisher     tags         title  
1      NaN       NaN      NaN        NaN      NaN           NaN  
2     1293       NaN        3        NaN       []          Food  
3      514       NaN        4        NaN       []  Electric Ave  
4     1151       NaN        6        NaN       []    This World  

[5 rows x 53 columns]