In [2]:
import sys

sys.path.append('/Users/datoapanta/Desktop/mma_2024/src/')
print(sys.path)                

['/Users/datoapanta/Desktop/mma_2024/src/models', '/Users/datoapanta/PycharmProjects/open_spiel', '/Users/datoapanta/PycharmProjects/open_spiel/build/python', '/Users/datoapanta/opt/anaconda3/envs/mma_2024/lib/python38.zip', '/Users/datoapanta/opt/anaconda3/envs/mma_2024/lib/python3.8', '/Users/datoapanta/opt/anaconda3/envs/mma_2024/lib/python3.8/lib-dynload', '', '/Users/datoapanta/opt/anaconda3/envs/mma_2024/lib/python3.8/site-packages', '/Users/datoapanta/Desktop/mma_2024/src/']


In [59]:
import config
from utils import audio_utils
from IPython.display import display
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer, LabelEncoder, LabelBinarizer
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle
from utils import audio_utils
import pickle
from utils import preprocessing

%load_ext autoreload
%autoreload 

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [61]:
# Splitting the data
data_splitted_dic = preprocessing.split_data(config.TRACKS_PATH)

# Get loaders
train_wav_paths, val_wav_paths, test_wav_paths = audio_utils.get_wav_paths(config.AUDIO_DIR, data_splitted_dic)
train_labels, val_labels, test_labels = preprocessing.get_labels(data_splitted_dic)

In [73]:
print(train_wav_paths[0])
print(data_splitted_dic['labels'].iloc[0])
print(train_labels[0])

print("\n", train_wav_paths[1])
print(data_splitted_dic['labels'].iloc[1])
print(train_labels[1])

print("\n", train_wav_paths[100])
print(data_splitted_dic['labels'].iloc[100])
print(train_labels[100])

/Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/000/000002.wav
Hip-Hop
[0 0 0 1 0 0 0 0]

 /Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/000/000005.wav
Hip-Hop
[0 0 0 1 0 0 0 0]

 /Users/datoapanta/Desktop/mma_2024/dataset/data/fma_small_wav/002/002096.wav
International
[0 1 0 0 0 0 0 0]


### Extracting 100 embeddings from VGGish

In [41]:
from vggish_model import VGGishModel
model = VGGishModel()

embeddings_train = model.forward(train_wav_paths[100])
print(embeddings_train.shape)

Using cache found in /Users/datoapanta/.cache/torch/hub/harritaylor_torchvggish_master


torch.Size([31, 128])


In [12]:
for i in range(100):
    embeddings_train = model.forward(train_wav_paths[i])
    output_file_path = f'embeddings/embedding_train_{i}.pkl'

    with open(output_file_path, 'wb') as f:
        pickle.dump(embeddings_train, f)